apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-apigateway
spec:
  package: xpkg.upbound.io/upbound/provider-aws-apigateway:v1.21.0
  runtimeConfigRef:
    name: aws-irsa-drc