apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudwatchlogs
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudwatchlogs:v1.20.1
  runtimeConfigRef:
    name: aws-irsa-drc  