apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdynamodbtables.database.platform.cloud
spec:
  group: database.platform.cloud
  names:
    kind: XDynamoDBTable
    plural: xdynamodbtables
  claimNames:
    kind: DynamoDBTable
    plural: dynamodbtables
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  description: >-
                    DynamoDB Table configuration parameters.
                  properties:
                    providerConfigRef:
                      type: object
                      description: "It tells the Provider which ProviderConfig to use when creating the managed resource"
                      properties:
                        name:
                          description: "Name of the ProviderConfig to use"
                          type: string
                          default: "default"
                    region:
                      type: string
                      description: >-
                        Region is the resources is located.
                    deletionPolicy:
                      type: string
                      description: >-
                        DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted
                        Either "Delete" or "Orphan" the external resource.
                      default: Delete
                    name:
                      type: string
                      description: >-
                        Name of the spa and its resources.
                    attribute:
                      description: >-
                        Required for hashKey and/or rangeKey.
                      items:
                        properties:
                          name:
                            type: string
                            description: >-
                              Name of the hashKey and/or rangeKey.
                          type:
                            enum:
                              - B #binary
                              - N #number
                              - S #string
                            type: string
                        required:
                          - name
                          - type
                        type: object
                      type: array
                    hashKey:
                      type: string
                      description: >-
                        Attribute to use as the hash (partition) key. Must also be defined as an attribute.
                    rangeKey:
                      type: string
                      description: >-
                        Name of the range key.
                    billingMode:
                      type: string
                      default: PAY_PER_REQUEST
                      description: >-
                        Controls how you are charged for read and write throughput 
                        and how you manage capacity. 
                        The valid values are PROVISIONED and PAY_PER_REQUEST. 
                        Defaults to PROVISIONED.
                    readCapacity:
                      type: number
                      description: >-
                        ThroughputConfig defines this table's read
                        capacity. Not required for on-demand mode.
                    writeCapacity:
                      type: number
                      description: >-
                        ThroughputConfig defines this table's write
                        capacity. Not required for on-demand mode.
                    globalSecondaryIndex:
                      description: >-
                        KeySchema specifies the attributes to create the
                        primary key for tables or indices.
                      items:
                        properties:
                          hashKey:
                            type: string
                            description: >-
                              Attribute to use as the hash (partition) key. Must also be defined as an attribute.
                          name:
                            type: string
                          rangeKey:
                            type: string
                            description: >-
                              Name of the range key;
                          readCapacity:
                            type: number
                            description: >-
                              ThroughputConfig defines this table's read
                              capacity. Not required for on-demand mode.
                          writeCapacity:
                            type: number
                            description: >-
                              ThroughputConfig defines this table's write
                              capacity. Not required for on-demand mode.
                          projectionType:
                            type: string
                            description: >-
                              One of ALL, INCLUDE or KEYS_ONLY where ALL projects every attribute into the index, 
                              KEYS_ONLY projects into the index only the table and index hash_key and sort_key attributes, 
                              INCLUDE projects into the index all of the attributes that are defined in non_key_attributes 
                              in addition to the attributes that thatKEYS_ONLY project.
                          nonKeyAttributes:
                            description: >-
                              Required for gsi
                              Only required with INCLUDE as a projection type; a list of attributes to project into the index. 
                              These do not need to be defined as attributes on the table.
                            items:
                              type: string
                            type: array
                        type: object
                        required:
                          - hashKey
                          - name
                          - readCapacity
                          - writeCapacity
                          - projectionType
                          - nonKeyAttributes
                      type: array
                    localSecondaryIndex:
                      description: >-
                        KeySchema specifies the attributes to create the
                        primary key for tables or indices.
                      items:
                        properties:
                          name:
                            type: string
                          rangeKey:
                            type: string
                            description: >-
                              Name of the range key
                          projectionType:
                            type: string
                          nonKeyAttributes:
                            description: >-
                              required for lsi
                            items:
                              type: string
                            type: array
                        type: object
                        required:
                          - name
                          - rangeKey
                          - projectionType
                          - nonKeyAttributes
                      type: array
                    tags:
                      description: Key-value map of tags. This object accepts the maximum number of 40 tags.
                      type: object
                      maxProperties: 40
                      x-kubernetes-preserve-unknown-fields: true
                  required:
                    - region
                    - name
                    - tags
              required:
                - parameters
            status:
              type: object
              properties:
                name:
                  type: string
                  description: >-
                    Name of the managed resource.
                arn:
                  type: string
                  description: >-
                    ARN of the managed resource.
